
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1230
    url: jdbc:mysql://localhost:3306/springboot
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083